# Generated by Django 3.2.5 on 2021-08-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('track_name', models.CharField(max_length=200)),
                ('album_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('end_time', models.DateTimeField()),
                ('ms_played', models.IntegerField()),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_stats.track')),
            ],
        ),
    ]
