# Generated by Django 3.2.5 on 2021-08-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='track_id',
            new_name='track',
        ),
        migrations.RemoveField(
            model_name='track',
            name='pub_date',
        ),
    ]
