# Generated by Django 3.2.5 on 2021-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_stats', '0004_alter_stream_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='track',
            name='album_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='stream',
            table='stream',
        ),
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
    ]
